language: python

python:
  - 3.5
  - 2.7

install: pip install pytest pytest-pep8 -r requirements.txt

script: py.test -vv --pep8 app.py

deploy:
  provider: script
  script: travis/deploy.sh
  on:
    branch: master
    condition: $TRAVIS_JOB_NUMBER = *.1
